### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#21]
In the configuration table it lists `tlsMode` shouldn't that be `database.tlsMode`?

<img width="925" alt="Screen Shot 2020-05-21 at 2 54 59 PM" src="https://user-images.githubusercontent.com/523312/82600152-0e332a80-9b73-11ea-930f-94c0eb751799.png">

**Comment by drpebcak** [comment]
Yep, thanks for pointing that out. Should be fixed now.
