### ISSUE TITLE
ARM64v8 - Raspberry Pi compatible docker image/Chart

### ISSUE THREAD

**Issue by arslanakhtar61** [FusionAuth/charts#23]
I want to deploy fusionAuth onto ARM64v8 - Raspberry Pi 4.  So far I have tried 
`
helm install fusionauth fusionauth/fusionauth  \
	--set database.user=fusionauth \
	--set database.password=fusionauth \
	--set database.root.user=postgres \
	--set database.root.password=postgres \
	--set database.host=postgresql.db \
	--set database.port=5432 \
	--set search.engine=database \
	--set image.repository=fusionauth/fusionauth-app \
	--set image.tag=latest
`

This gives the following error, from container log => container "fusionauth" in pod "fusionauth-97988bb4d-596zp" is waiting to start: PodInitializing

postgres db container is already up, running and accessible with k8s cluster,

**Comment by drpebcak** [comment]
Fusionauth only publishes images for linux/amd64. You would have to create your own docker image containing fusionauth.

Additionally, the containers used to check that postgres and elasticsearch are ready, are also only supported on linux/amd64.

This repo is only for the chart (and is community maintained) so there is nothing I can do here to solve this for you.

**Comment by drpebcak** [comment]
This will make things slightly easier for you - it replaces the image used for initContainers with one that should work for arm. Haven't tested it yet, but it should work.

https://github.com/FusionAuth/charts/pull/24
