### ISSUE TITLE
 initContainers: wait-for-db is missing the terminal/shell argument

### ISSUE THREAD

**Issue by arslanakhtar61** [FusionAuth/charts#25]
Under master branch chart/templates/deployment.yaml, the    initContainers: wait-for-db is now using the multiarch image => busybox:latest
```
initContainers:
        - name: wait-for-db
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          args:
            - >
              set -x;
              while [[ "$(nc -zv '{{- .Values.database.host -}}' {{ .Values.database.port }} &> /dev/null; echo $?)" != 0 ]]; do
                echo '.'
                sleep 15;
              done
```

This throws an error saying that "_no such file or directory_".  
The solution is to identify and add the kind of terminal (or shell) that is available on the busybox:latest image by using  

```
$ docker inspect busybox:latest

"Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"sh\"]"
            ]
```
Then modify the chart/templates/deployment.yaml by specifying the correct available shell for busybox image as following:
```
initContainers:
        - name: wait-for-db
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
         args:
            - /bin/sh
            - -c
              set -x;
              while [[ "$(nc -zv '{{- .Values.database.host -}}' {{ .Values.database.port }} &> /dev/null; echo $?)" != 0 ]]; do
                echo '.'
                sleep 15;
              done
```
This solution works. I can create a pull request if I am in the right direction.

**Comment by drpebcak** [comment]
Please open a PR. This is similar to how it was before we started using busybox (just with bash instead).

**Comment by drpebcak** [comment]
Got impatient and pushed this myself. Should fix head of master.
