### ISSUE TITLE
ElasticSearch credentials appear to be discarded or ignored during provisioning

### ISSUE THREAD

**Issue by ShaunLadd** [FusionAuth/charts#33]
I am using the latest helm chart and passing in the connection string for our Elastic server. However during provisioning I receive a 401 http response and it appears the credentials were dropped from the connection string. Has anyone seen this before? This is with FusionAuth 1.19.7. I did not have this problem with 1.16.1. If I login to the fusionAuth pod I can see the credential string setup properly as the SEARCH_SERVERS and I can manually connect to ElasticSearch using it:

SEARCH_SERVERS=http://elastic:V9Q1nbqUK82caeche6514i0i@elasticsearch-cluster-es-http:9200
(that is a temporary password)

2020-09-23 12:57:55.025 PM INFO com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://elasticsearch-cluster-es-http:9200]
2020-09-23 12:57:55.614 PM INFO com.inversoft.maintenance.search.ElasticsearchMaintenanceModeSearchService - Missing search index [fusionauth_user]
2020-09-23 12:57:55.620 PM INFO com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://elasticsearch-cluster-es-http:9200]
2020-09-23 12:57:55.685 PM ERROR com.inversoft.maintenance.search.ElasticsearchMaintenanceModeSearchService - Failed to create index [fusionauth_user]. Reason + [org.elasticsearch.client.ResponseException: method [GET], host [http://10.20.30.99:9200], URI [/], status line [HTTP/1.1 401 Unauthorized]

Please let me know what other information you need and I can submit it.

**Comment by drpebcak** [comment]
@robotdan this might be something that has changed inside fusionauth itself.

**Comment by ShaunLadd** [comment]
also, after changing to docker image 1.19.7, I also get this error in the  logs:

2020-09-25 6:15:11.174 PM ERROR org.primeframework.mvc.servlet.PrimeFilter - Error encountered
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.primeframework.mvc.workflow.MVCWorkflow was bound.
  while locating org.primeframework.mvc.workflow.MVCWorkflow

1 error

**Comment by robotdan** [comment]
I'll take a look.

**Comment by robotdan** [comment]
@ShaunLadd are you using the `:1.19.7` tag, or `:latest` and if latest, can you confirm you have explicitly pulled the latest image which is `:1.19.7`?

**Comment by robotdan** [comment]
I stood up an Aiven instance of ES via Digital Ocean, and I think I recreated. I think it is related to our usage of Elasticsearch Sniffer. 

In reading this: https://www.elastic.co/blog/elasticsearch-sniffing-best-practices-what-when-why-how

> When not to sniff?
>  * You’re working with cloud providers. 


So perhaps we need to leave this off by default. We added it because it makes our lives a bit easier in our FusionAuth Cloud deployments. But it looks like in these types of configurations where the endpoint that we are hitting is already a clustered or managed endpoint it just gets confused.

**Comment by robotdan** [comment]
See this issue, I think we need to disable this by default, or at least let it be disabled. 
https://github.com/FusionAuth/fusionauth-issues/issues/893

**Comment by drpebcak** [comment]
Disabled by default is probably least surprising for people.

**Comment by drpebcak** [comment]
I'm going to close this one now since the issue doesn't appear to be related to the chart.

**Comment by ShaunLadd** [comment]
@robotdan I am using the tagged image 1.19.7.  Please let me know if you publish another image and disable the sniffing

**Comment by robotdan** [comment]
@ShaunLadd you can follow this issue -> FusionAuth/fusionauth-issues#893 we'll fix it there.

**Comment by robotdan** [comment]
FYI, FusionAuth/fusionauth-issues#893 is available in 1.19.8 if you want to try it out. The sniffer is now off by default.

**Comment by Xiakitl** [comment]
Hi everybody, 

I receive the same exception as @ShaunLadd in 1.19.7. 

`No implementation for org.primeframework.mvc.workflow.MVCWorkflow was bound. 
while locating org.primeframework.mvc.workflow.MVCWorkflow`

Has somebody encountered the same error and knows how to fix it? (Should I open a new issue?) 

Thanks in advance :)
