### ISSUE TITLE
Register chart repository with artifacthub.io

### ISSUE THREAD

**Issue by MatthiasLohr** [FusionAuth/charts#42]
Hi,

first thank you for this great work (FusionAuth as well as the helm chart)!

I have a small suggestion: It took a while for me to find your helm chart. The main search portal for finding helm charts is https://artifacthub.io/. I would like to ask and to suggest, if you would be willing to register your helm chart repository on that site, so that your helm chart can be found more easily. What do you think about that?

Best regards
Matthias

**Comment by mooreds** [comment]
@MatthiasLohr thanks for the suggestion!

What needs to be done to do that? It looks from [the docs here](https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories) like this is a one and done task, just pointing the hub at this git repo. Is that correct?

Right now helm and k8s support are community driven; can you submit the helm charts?

**Comment by MatthiasLohr** [comment]
> What needs to be done to do that? It looks from [the docs here](https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories) like this is a one and done task, just pointing the hub at this git repo. Is that correct?
Yep, exactly

> Right now helm and k8s support are community driven; can you submit the helm charts?
I can add it, if you agree that I use the name "FusionAuth" for the repository link (don't want to do that without your permission). I can also add you as an administrator after I created the link.

**Comment by MatthiasLohr** [comment]
Just created it, looks now like this: https://artifacthub.io/packages/search?page=1&ts_query_web=fusionauth&org=fusionauth

**Comment by mooreds** [comment]
Awesome, that's great! Thanks for doing this.

What do you need to add us as an admin? Email? github username? something else?

**Comment by MatthiasLohr** [comment]
I would need your username on ArtifactHub.

**Comment by mooreds** [comment]
@MatthiasLohr I just signed up, it's `fusionauth`.

Also, @drpebcak is the primary maintainer of this repo. Taylor, would you like to be added as an admin on artifacthub?

**Comment by MatthiasLohr** [comment]
@mooreds you should have received an invitation. Think we can close this issue now, however I can still add @drpebcak to the group (and I guess you will also be able to do that after you accepted the invitation).

**Comment by drpebcak** [comment]
@mooreds Sure, would probably be useful.

**Comment by mooreds** [comment]
@drpebcak great! please let me know what your artifactory.io username is and I'll add you.

Thanks again @MatthiasLohr for suggesting this!

**Comment by drpebcak** [comment]
@mooreds its the same as my github username, `drpebcak`.

**Comment by mooreds** [comment]
@MatthiasLohr 

I can't seem to add `drpebcak` as a user. Did you add the `fusionauth` user as an admin?

**Comment by MatthiasLohr** [comment]
@drpebcak I sent you an invite.
@mooreds I can't see any option for that, neither any indicator that there is such a concept as admin or non-admin. Log In, go to control panel, select fusionauth as context (in top right corner, right under your profile picture), select the members tab, in the headline should be an invite button.

**Comment by mooreds** [comment]
@MatthiasLohr Ah, thanks so much! I was missing the "change the context" step. 

Cheers!
