### ISSUE TITLE
key rootpassword in Secret fusionauth/fusionauth-credentials should be optional

### ISSUE THREAD

**Issue by sean-mcgimpsey** [FusionAuth/charts#43]
For managed Database services, the fusionauth documentation states that the root password configuration option should not be specified, see ; https://fusionauth.io/docs/v1/tech/guides/silent-mode/

Though, using this chart without specifying `database.root.password` results in a database config error. 

This chart should be fixed so that `database.root.password` is optional.

**Comment by sean-mcgimpsey** [comment]
#44 raised

**Comment by drpebcak** [comment]
Just released 0.9.2 with this fix included.
