### ISSUE TITLE
Improvement: Env vars should be moved to configmap

### ISSUE THREAD

**Issue by sean-mcgimpsey** [FusionAuth/charts#45]
Given that FusionAuth is highly configurable via environment variables, it makes sense to move these variables into a separate ConfigMap, which is then consumed by the pod. 

Not so much an issue, but an improvement.

**Comment by drpebcak** [comment]
Does this gain us anything?

**Comment by drpebcak** [comment]
Sounds kind of cool! I'll throw a PR together

**Comment by drpebcak** [comment]
One issue here is that we have some config that comes from a secret - so the configmap can't have 'everything' in it. You would need to mount the secret and the configmap. Not a showstopper, just something to be aware of.

**Comment by johnjeffers** [comment]
Closing since this is well over 2 years old and there doesn't seem to be any further interest.
