### ISSUE TITLE
Don't hardcode busybox registry in test-connection.yaml

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#55]
Is it possible to not hardcode the `busybox` Docker image in https://github.com/FusionAuth/charts/blob/master/chart/templates/tests/test-connection.yaml#L15 and use the parent `initImage:repository` value if defined. If not defined, fallback to using the hardcoded `busybox`.

The reason is we are using isolation and it required all the Docker containers be hosted on our private registry.  As it currently stands, we don't have a way to override the registry for this.

**Comment by drpebcak** [comment]
This is addressed in #56

**Comment by nodesocket** [comment]
Thanks so much. Can you roll another release `0.9.3` with this supported?

**Comment by drpebcak** [comment]
0.9.3 is being built right now. should be available within a few minutes or so.
