### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by SwitchTV-BenBettridge** [FusionAuth/charts#64]
0.9.4 was recently released from this repo, but isn't yet available in the https://fusionauth.github.io/charts/ repository - any ETA on this? Thanks.

**Comment by mooreds** [comment]
@lanceatdr anything you can do to help?

**Comment by drpebcak** [comment]
This was being worked on here: https://github.com/FusionAuth/charts/pull/61

This was merged already however, and I think there is still a piece missing.

**Comment by lanceatdr** [comment]
I recreated the process that was previously used via travis.  It looks like
indexing helm repos in github may have changed a bit since I did it last.
I'll have a look and can try and update the process.

**Comment by drpebcak** [comment]
Closing this because we've done a release using the new process. Latest right now is 0.10.2.
