### ISSUE TITLE
Support for setting resources.requests in initContainers 

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#67]
**Is your feature request related to a problem? Please describe.**

Can you add support for passing `resources.requests` into both the `initContainers` `wait-for-db` and `wait-for-search`? We require specifying a `resources.requests` for every single pod we deploy and currently there is no way to provide this.

See: https://github.com/FusionAuth/charts/blob/master/chart/templates/deployment.yaml#L35

**Comment by IbraheemAlSaady** [comment]
+1

**Comment by drpebcak** [comment]
This should be resolved with 0.10.2
