### ISSUE TITLE
Ingress falls back into wrong api version for recent k8s versions

### ISSUE THREAD

**Issue by miaucl** [FusionAuth/charts#69]
**Describe the bug**
I am trying to set up the fusionauth chart using the ingress option. On a clean installation, I run into the problem that the ingress uses an api which is not compatible with my kubernetes installation.

**Docker version and underlying OS**

Running on macOS, virtualbox-driver for minikube, kubernetes:
```bash
kubectl version
>> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
>> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
``` 

**To Reproduce**
1. Run 
```bash
helm install fa-test fusionauth/fusionauth --set database.user=fusionauth --set database.password=fusionauth --set database.host=fusionauthdb --set search.engine=database --set ingress.enabled=true
>> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"
```

**Expected behavior**
I guess the new api version is no longer `networking.k8s.io/v1beta1` but `networking.k8s.io/v1` and therefore following part in the `_helper`:
```
{{/*
Set apiVersion for ingress
*/}}
{{- define "fusionauth.ingressApiVersion" -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
networking.k8s.io/v1beta1
{{- else -}}
extensions/v1beta1
{{- end -}}
{{- end -}}
```
falls back into the even older api.

Otherwise there is not much difference between this ingress definition and the standard one obtained by `helm create …`.

**Comment by drpebcak** [comment]
0.10.3 contains this fix and is being created right now.
