### ISSUE TITLE
Please create a helm charts for the latest FusionAuth version 1.32.1

### ISSUE THREAD

**Issue by darkeagle1337** [FusionAuth/charts#78]
Since one week the version 1.31.1 of FusionAuth is available. https://fusionauth.io/docs/v1/tech/release-notes/#version-1-32-1
But the Helm Charts are still stuck on 1.30.1.

Can you please create a new FusionAuth Helm Charts which supports the latest version of FusionAuth?

Thanks a lot in advance.
Christian

**Comment by mooreds** [comment]
I think this PR applies: https://github.com/FusionAuth/charts/pull/77 and just needs to be merged.

**Comment by mooreds** [comment]
#77 just got merged. Thanks for calling our attention to this, @darkeagle1337 .

**Comment by darkeagle1337** [comment]
Could make a release of this master version?
