### ISSUE TITLE
FusionAuth wants to be a K8S Operator

### ISSUE THREAD

**Issue by kferrone** [FusionAuth/charts#80]
**Is your feature request related to a problem? Please describe.**
No k8s yaml to submit which creates fusionauth stuff. 

**Is your feature request related to a way you would like fusionauth extended? Please describe.**
Yes, Fusionauth has the perfect kind of data for a k8s operator. 

**Describe the solution you'd like**
Kubernetes Operator for FusionAuth

**Describe alternatives you've considered**
Make my own, erm, that's hard to do. 
Only option is lame hacky ci scripts posting curl requests.

**Comment by mooreds** [comment]
Added an issue in our central issue tracking repo. Thanks for the suggestion @kferrone !

**Comment by drpebcak** [comment]
Closing this one since it's outside the scope of the chart!
