### ISSUE TITLE
Update image tag as part of the FusionAuth release process to keep it tracking with latest 

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/charts#81]
Update image tag as part of the FusionAuth release process to keep it tracking with latest

**Comment by johnjeffers** [comment]
This is something I'm going to be taking on soon. Just trying to figure out how we want to do this.

Here are the options I'm considering:

1. Version the helm charts with the same version number as the FusionAuth release. In other words, helm chart 1.48.1 corresponds to FusionAuth release 1.48.1. The problem with this approach is that we have no way to designate changes to the chart itself that are independent of the FusionAuth release version.

2. Use the FusionAuth release version as a base, but extend it with some indicator of chart changes. Something like `1.48.1-1` for the 1st version of the 1.48.1 chart, `1.48.1-2` for the 2nd version, etc. I like that this is straightforward, but I don't love that that breaks semver conventions.

3. Keep versioning the chart as we have been, independent of the FusionAuth release, and mention in the release notes whenever we update the chart with a new default version of the app.

Whatever method we choose, we should be sure that we don't break things for anyone that has manually overridden the default version.

**Comment by robotdan** [comment]
Option 1: This is why I have hesitated to do this in the past because it doesn't allow you to designate changes to the chart outside of a version change to FusionAuth. 

Option 2: It is important for me to stay semver compliant.

**Comment by johnjeffers** [comment]
Let's go with option 3 then. If we want to stay semver compliant, we should probably bump the chart version to 1.0.0 to indicate that it's production ready. Chart 1.0.0 will use FusionAuth 1.48.1, and I'll mention that in the release notes as well as in the important changes section in the readme.

**Comment by mmanes** [comment]
Will we still update the image version with every release, i.e. if no other chart changes are made, Chart 1.0.1 will be released with FusionAuth image 1.49.0?

**Comment by johnjeffers** [comment]
Yes, that feels to me like the right way to go, and lines up with most other charts I've used. To sum up:

* If a new app version is released, we release a new chart, even if there are no other changes to the chart.
* The latest chart version should always default to the latest app version

**Comment by johnjeffers** [comment]
This is resolved in the [1.0.0 release](https://github.com/FusionAuth/charts/releases/tag/1.0.0).
