### ISSUE TITLE
Annotations support for FusionAuth ServiceAccount

### ISSUE THREAD

**Issue by ladogolijashvili** [FusionAuth/charts#89]
**Is your feature request related to a problem? Please describe.**
We want to communicate with Elasticsearch with EKS ServiceAccount throught IAM roles, for that serviceaccount must have annotations about IAM role it must assume, right now chart is only creating ServiceAccount but there is no possibility to add annotations. I can add feature but as i see in README history, this repo is no longer maintained by community.
 
**Describe alternatives you've considered**
We are deploying helm with terraform so creating serviceaccount and rolebindings outside helm chart is possible but as helm is controlling deployment pods wont be available to use terraform created serviceaccount

**Comment by mooreds** [comment]
Thanks for the feedback @ladogolijashvili . Is it possible for you to create a PR documenting the changes you'd like?

**Comment by johnjeffers** [comment]
This change has been merged and will go out in the next chart release!
