### ISSUE TITLE
Explicitly define image version tags

### ISSUE THREAD

**Issue by mmanes** [FusionAuth/charts#93]
**Is your feature request related to a problem? Please describe.**
Using an image tag of `latest` can cause problems when dependent images introduce breaking changes or when a cached, older version of the image is used. Explicitly defining image tags allows us to ensure that what we test is what will be deployed.

**Describe the solution you'd like**
Use a specific image tag for all containers, specifically the `busybox` image used for our initContainers.

**Comment by johnjeffers** [comment]
Fixed in https://github.com/FusionAuth/charts/pull/99
